language: java
os:
- linux
jdk:
- oraclejdk8
all_branches: true
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarcloud:
    organization: zaraka-github
    token:
      secure: 20d8bb4684014c126bb703586239c81d845782b9
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
- mvn jfx:native assembly:single
- pwd
- ls target
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
deploy:
  provider: releases
  api_key:
    secure: bEvKmdPkcR1PUfRIqMyJvPyk9lu2MK35SreDbVKtFiy1ropY1v0CraqyBZ+ErV40
  file:
    - "/home/travis/build/Zaraka/GruntArbiter/target/GruntArbiter-$TRAVIS_TAG.jar"
    - "/home/travis/build/Zaraka/GruntArbiter/target/GruntArbiter-$TRAVIS_TAG-Linux-native.zip"
  on:
    repo: Zaraka/GruntArbiter
    tags: true
