language: java

os:
  - linux
  - osx

jdk:
  - oraclejdk8

branches:
  only:
  - master

addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
      organization: "zaraka-github"
      token:
        secure: "20d8bb4684014c126bb703586239c81d845782b9"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn jfx:native assembly:single
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

deploy:
  provider: releases
  file: "target/*.zip"
  skip_cleanup: true
  on:
    tags: true