language: java

jdk:
  - oraclejdk8

branches:
  only:
  - master

addons:
  apt:
    packages:
      - oracle-java8-installer

deploy:
  provider: releases
  file: "target/*.zip"
  skip_cleanup: true
  on:
    tags: true