version: '{build}'
os: Windows Server 2012
install:

build_script:
  - mvn jfx:native assembly:single
deploy:
  provider: GitHub
  auth_token:
    secure: bEvKmdPkcR1PUfRIqMyJvPyk9lu2MK35SreDbVKtFiy1ropY1v0CraqyBZ+ErV40
  artifact: target/*.zip
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true