version: '{build}'
os: Windows Server 2012
install:

build_script:
  - mvn jfx:native assembly:single
deploy:
  provider: GitHub
  auth_token:
    secure: g+UnOoH3zZtLf3Lp2Iv6rUCZYFxki+3+A+T9DQ92JptmsfiAGRsaJ3CD7V0xP8S2
  artifacts:
  - path: C:\projects\gruntarbiter\target\*.zip
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true